openapi: 3.0.1
info:
  title: Stdent  API
  description: API for managing Students
  version: 1.0.0
paths:
  /students:
    get:
      summary: Get all students
      operationId: getAllStudents
      responses:
        '200':
          description: List of Students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
    post:
      summary: Add a new student
      operationId: addstudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: Student added
        '400':
          description: Invalid student input

  /students/{id}:
    get:
      summary: Get Stdent by id
      operationId: getStudentById
      parameters:
        - name: id
          in: path
          required: true
          description: id  of the Student
          schema:
            type: number
      responses:
        '200':
          description: Student details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '404':
          description: student not found


components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: number
          example: 12
        name:
          type: string
          example: "Vayu"
        age:
          type: number
          example: 21

        grade:
          type: string
          example: "A"
        email:
          type: string
          example: "any thing about"


