


  
  CREATE TABLE  ecommerceapp.product_category (
   id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  sku VARCHAR(255) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  unit_price DECIMAL(13,2) DEFAULT NULL,
  image_url VARCHAR(255) DEFAULT NULL,
  active  CHAR(1) DEFAULT 1,
  units_in_stock NUMBER DEFAULT NULL,
   date_created TIMESTAMP(8) DEFAULT NULL,
  last_updated TIMESTAMP(8) DEFAULT NULL,
  category_id NUMBER  NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES product_category (id));



-- -----------------------------------------------------
-- Table full-stack-ecommerce.product
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ecommerceapp.product (
  id NUMBER NOT NULL AUTO_INCREMENT,
  sku VARCHAR(255) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  unit_price DECIMAL(13,2) DEFAULT NULL,
  image_url VARCHAR(255) DEFAULT NULL,
  active BIT DEFAULT 1,
  units_in_stock INT(11) DEFAULT NULL,
   date_created DATETIME(6) DEFAULT NULL,
  last_updated DATETIME(6) DEFAULT NULL,
  category_id BIGINT(20) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES product_category (id)
) 

